'use strict';

/**
 * Group-by (`{}`) and transform (`|pattern|update,delete|`) runtime support
 * (design.md D4: ported entirely — no interpreter-exported equivalent).
 * Mechanics verified directly against jsonata's own `evaluateGroupExpression`
 * / `evaluateTransformExpression` (src/jsonata.js) since that is the
 * conformance-suite-authoritative behavior.
 *
 * Group-by: for each source item, each `{key: value}` pair's key expression
 * is evaluated with `$` = that item; matching items bucket by key (their
 * *pair index* must stay consistent — the same key produced by two
 * *different* pair entries is D1009). Each bucket's value expression is
 * evaluated once with `$` = the bucket's accumulated data (a single item if
 * exactly one matched, the array of items if more than one — the same shape
 * `RT.collapse` produces).
 *
 * Transform: clones the source (structural.cloneFn), evaluates `pattern`
 * against the CLONE so any matched object/array is a live reference into
 * it, then mutates each match in place via the `update`/`delete` callbacks
 * — no special "location-aware" navigation needed, ordinary path
 * navigation already yields references for object/array values.
 */

const RT = require('./values');
const { JsonataEvaluationError } = require('../errors');

function err(code, extra) {
  return new JsonataEvaluationError(code, extra);
}

/**
 * Single-pass left-fold of jsonata's `fn.append` over a whole run of values.
 *
 * Folding jsonata's pairwise `fn.append` allocates (and copies) a fresh array per
 * item, so accumulating one group-by bucket of `n` items cost O(n^2) slots -
 * 354 ms for a 20,000-item bucket, 11.2 s for 80,000 (jsonata2js.md JS-4/M-2),
 * which real data with one dominant key (log lines by day, orders by status)
 * hits directly. These three functions accumulate into ONE array instead and
 * reproduce `fn.append`'s observable rules exactly:
 *   - an `undefined` item contributes nothing;
 *   - exactly one contributing item stays itself, scalar OR array
 *     (`append(undefined, [1,2])` is `[1,2]`, not `[[1,2]]`);
 *   - two or more flatten one level into a single fresh array (the first
 *     item is copied, never mutated in place).
 */
function appendAcc() {
  return { count: 0, first: undefined, out: null };
}

function appendAccPush(acc, v) {
  if (v === undefined) return;
  acc.count++;
  if (acc.count === 1) {
    acc.first = v;
    return;
  }
  if (acc.out === null) {
    // Copy: the caller still owns `first`, and jsonata's `concat` never
    // mutated it either.
    acc.out = Array.isArray(acc.first) ? acc.first.slice() : [acc.first];
  }
  const out = acc.out;
  if (Array.isArray(v)) {
    for (let i = 0; i < v.length; i++) out.push(v[i]);
  } else {
    out.push(v);
  }
}

function appendAccValue(acc) {
  if (acc.count === 0) return undefined;
  return acc.count === 1 ? acc.first : acc.out;
}

/**
 * Ports jsonata's `reduceTupleStream` binding merge for one bucket: each
 * binding name *appends* (not overwrites) across every tuple that carries it,
 * so `valueFn` sees every matching tuple's value for that name (e.g. `#$i`
 * across a repeated key becomes `[0,1]`).
 *
 * Accumulated per name in one pass - the previous shape rebuilt the whole
 * merged bindings object per tuple (`Object.assign({}, bindings)` plus one
 * pairwise append per name), which is the second half of JS-4's quadratic
 * behaviour.
 */
function mergeTupleBindings(data) {
  if (data.length === 1) return data[0].b;
  let accs = null;
  for (let i = 0; i < data.length; i++) {
    const b = data[i].b;
    if (!b) continue;
    if (accs === null) accs = new Map();
    for (const key of Object.keys(b)) {
      let acc = accs.get(key);
      if (acc === undefined) {
        acc = appendAcc();
        accs.set(key, acc);
      }
      appendAccPush(acc, b[key]);
    }
  }
  if (accs === null) return undefined;
  // Object.create(null) - a binding name is never `__proto__` in practice,
  // but the group-by result objects are built that way too (CODE-REVIEW.md H5).
  const merged = Object.create(null);
  for (const [key, acc] of accs) merged[key] = appendAccValue(acc);
  return merged;
}

/**
 * `tuples`: the path-tuple array (`{v, p, b}`) feeding this group-by -
 * `t.b` carries any `@$`/`#$` bindings active for that tuple (tuple-stream
 * mode). `pairs`: array of `{ keyFn, valueFn }`, both `(v, tupleBindings)
 * => value` closures generated by the translator (`$` rebound to
 * `v`/the bucket's collapsed data respectively; `__tb` to the tuple's own
 * bindings, or the bucket's merged bindings for `valueFn`).
 */
function groupBy(tuples, pairs) {
  let items = tuples.length === 0 ? [{ v: undefined, b: undefined }] : tuples;

  const order = [];
  const buckets = Object.create(null); // key -> { pairIndex, data: [] }

  for (const item of items) {
    for (let pairIndex = 0; pairIndex < pairs.length; pairIndex++) {
      const key = pairs[pairIndex].keyFn(item.v, item.b);
      if (key === undefined) continue;
      if (typeof key !== 'string') {
        throw err('T1003', { value: key });
      }
      if (Object.prototype.hasOwnProperty.call(buckets, key)) {
        if (buckets[key].pairIndex !== pairIndex) {
          throw err('D1009', { value: key });
        }
        buckets[key].data.push(item);
      } else {
        buckets[key] = { pairIndex, data: [item] };
        order.push(key);
      }
    }
  }

  // Object.create(null) - see translator.js#genObjectConstructor's comment / CODE-REVIEW.md H5.
  const result = Object.create(null);
  for (const key of order) {
    const bucket = buckets[key];
    // jsonata accumulates a bucket with `fn.append`, not by collecting items
    // and collapsing: an item that is itself an array CONCATENATES into what
    // the bucket already holds. `$zip(nums,nums){"k":$}` is
    // `{"k":[1,1,2,2,3,3]}`, not three pairs (§13.5 of the conformance note).
    const acc = appendAcc();
    for (const t of bucket.data) appendAccPush(acc, t.v);
    const context = appendAccValue(acc);
    const bindings = mergeTupleBindings(bucket.data);
    const value = pairs[bucket.pairIndex].valueFn(context, bindings);
    if (value !== undefined) result[key] = value;
  }
  return result;
}

/**
 * `groupBy` for a value-mode stream: no `@$`/`#$` bindings to merge (the
 * translator only routes here when the source path and every key/value
 * expression are free of `%`/`@$`/`#$`), so buckets hold plain values and
 * `keyFn`/`valueFn` get `undefined` for the bindings argument. Saves one tuple
 * object per source element — 2,000 of them for a group-by over a
 * 2,000-element array.
 */
function groupByValues(values, pairs) {
  const items = values.length === 0 ? [undefined] : values;

  const order = [];
  const buckets = Object.create(null); // key -> { pairIndex, data: [] }

  for (let i = 0; i < items.length; i++) {
    const v = items[i];
    for (let pairIndex = 0; pairIndex < pairs.length; pairIndex++) {
      const key = pairs[pairIndex].keyFn(v, undefined);
      if (key === undefined) continue;
      if (typeof key !== 'string') {
        throw err('T1003', { value: key });
      }
      const existing = buckets[key];
      if (existing !== undefined) {
        if (existing.pairIndex !== pairIndex) {
          throw err('D1009', { value: key });
        }
        existing.data.push(v);
      } else {
        buckets[key] = { pairIndex, data: [v] };
        order.push(key);
      }
    }
  }

  // Object.create(null) - see translator.js#genObjectConstructor's comment / CODE-REVIEW.md H5.
  const result = Object.create(null);
  for (const key of order) {
    const bucket = buckets[key];
    // `fn.append` accumulation - see `groupBy`.
    const acc = appendAcc();
    for (const v of bucket.data) appendAccPush(acc, v);
    const value = pairs[bucket.pairIndex].valueFn(appendAccValue(acc), undefined);
    if (value !== undefined) result[key] = value;
  }
  return result;
}

/**
 * `sortTuples(tuples, keyDescriptors)` — stable multi-key sort over path
 * tuples (`{v, p}`), preserving `%` parent-chain access for each key
 * expression. `keyDescriptors`: array of `{ key: (v, parentTuple) => value,
 * desc: boolean }`. Ported from jsonata's own `evaluateSortExpression`
 * comparator: `undefined` always sorts last regardless of direction;
 * comparing values of different types is T2007; a non-string/non-number
 * key value is T2008.
 *
 * Each key expression is evaluated exactly ONCE per element (a Schwartzian
 * transform) instead of on every comparison, which for `n` elements cuts key
 * evaluations from O(n log n) to O(n) — the dominant cost of a sort over a
 * non-trivial key. `Array.prototype.sort` has been required to be stable
 * since ES2019 (V8 uses TimSort), so the previous decorate-with-index step is
 * no longer needed for stability either; ties fall back to the original index
 * only to keep the comparator total.
 */
function sortTuples(tuples, keyDescriptors) {
  const n = tuples.length;
  // A 0/1-element sort must not evaluate any key expression at all: the old
  // comparator was never invoked in that case either.
  if (n < 2) return tuples.slice();
  const k = keyDescriptors.length;
  const columns = new Array(k);
  for (let d = 0; d < k; d++) {
    const keyFn = keyDescriptors[d].key;
    const col = new Array(n);
    for (let i = 0; i < n; i++) {
      const t = tuples[i];
      col[i] = keyFn(t.v, t.p, t.b);
    }
    columns[d] = col;
  }
  return reorderBy(tuples, sortedOrder(columns, keyDescriptors, n));
}

/**
 * `sortTuples` for a value-mode stream (`translator#genSortExpr`'s fast path):
 * a *terminal* `^()` whose source and keys never touch `%`/`@$`/`#$` cannot
 * observe a tuple, so it sorts the values themselves — which also keeps the
 * whole preceding navigation in value mode.
 */
function sortValues(values, keyDescriptors) {
  const n = values.length;
  if (n < 2) return values.slice();
  const k = keyDescriptors.length;
  const columns = new Array(k);
  for (let d = 0; d < k; d++) {
    const keyFn = keyDescriptors[d].key;
    const col = new Array(n);
    for (let i = 0; i < n; i++) col[i] = keyFn(values[i], undefined, undefined);
    columns[d] = col;
  }
  return reorderBy(values, sortedOrder(columns, keyDescriptors, n));
}

function reorderBy(items, order) {
  const out = new Array(order.length);
  for (let i = 0; i < order.length; i++) out[i] = items[order[i]];
  return out;
}

/**
 * True if no comparison of `col`'s values can raise T2007/T2008: every defined
 * key is a string or a number, and they are all the same one. `undefined` is
 * exempt - it sorts last without being compared by type.
 */
function comparableColumn(col) {
  let type;
  for (let i = 0; i < col.length; i++) {
    const t = typeof col[i];
    if (t === 'undefined') continue;
    if (t !== 'string' && t !== 'number') return false;
    if (type === undefined) type = t;
    else if (t !== type) return false;
  }
  return true;
}

function sortedOrder(columns, keyDescriptors, n) {
  const k = columns.length;
  const order = new Array(n);
  for (let i = 0; i < n; i++) order[i] = i;
  // Which comparison a heterogeneous sort trips over first decides whether it
  // reports T2008 (a key that is neither string nor number) or T2007 (two keys
  // of different types), so a sort that CAN throw is run in jsonata's own
  // comparison order. One that cannot - every real sort - keeps the engine's
  // faster `Array.prototype.sort`, which produces an identical order because
  // both are stable and the comparator below is total.
  let canThrow = false;
  for (let d = 0; d < k && !canThrow; d++) canThrow = !comparableColumn(columns[d]);
  const compare = (ia, ib) => {
    for (let d = 0; d < k; d++) {
      const col = columns[d];
      const aa = col[ia];
      const bb = col[ib];
      const atype = typeof aa;
      const btype = typeof bb;
      let comp = 0;
      if (atype === 'undefined') {
        comp = btype === 'undefined' ? 0 : 1;
      } else if (btype === 'undefined') {
        comp = -1;
      } else if (!(atype === 'string' || atype === 'number') || !(btype === 'string' || btype === 'number')) {
        throw err('T2008', { value: !(atype === 'string' || atype === 'number') ? aa : bb });
      } else if (atype !== btype) {
        throw err('T2007', { value: aa, value2: bb });
      } else if (aa === bb) {
        comp = 0;
      } else {
        comp = aa < bb ? -1 : 1;
        if (keyDescriptors[d].desc) comp = -comp;
      }
      if (comp !== 0) return comp;
    }
    return ia - ib;
  };
  if (canThrow) return mergeSortOrder(order, compare);
  order.sort(compare);
  return order;
}

/**
 * Top-down merge sort, matching jsonata's own `fn.sort` (`functions.js`) -
 * split in half, sort the left half completely, then the right, then merge
 * comparing the two heads. `Array.prototype.sort` produces the same ORDER
 * (both are stable and the comparator is total), but a different sequence of
 * comparisons - which decides which bad key pair a heterogeneous `^()` trips
 * over first, and so whether it reports T2007 or T2008.
 *
 * Written over index ranges with one scratch buffer rather than jsonata's
 * `slice`-per-level recursion: the comparison sequence is identical, but the
 * allocations are O(1) instead of O(n log n).
 *
 * Taking from the left on a non-positive comparison keeps it stable.
 */
function mergeSortOrder(order, cmp) {
  const n = order.length;
  if (n > 1) mergeSortRange(order, new Array(n), 0, n, cmp);
  return order;
}

/** Sorts `a[lo, hi)` in place, using `buf` as scratch. */
function mergeSortRange(a, buf, lo, hi, cmp) {
  if (hi - lo <= 1) return;
  const mid = lo + ((hi - lo) >> 1);
  mergeSortRange(a, buf, lo, mid, cmp);
  mergeSortRange(a, buf, mid, hi, cmp);
  let i = lo;
  let j = mid;
  let o = lo;
  while (i < mid && j < hi) buf[o++] = cmp(a[i], a[j]) > 0 ? a[j++] : a[i++];
  while (i < mid) buf[o++] = a[i++];
  while (j < hi) buf[o++] = a[j++];
  for (let k = lo; k < hi; k++) a[k] = buf[k];
}

function isPlainObject(v) {
  return v !== null && typeof v === 'object' && !Array.isArray(v);
}

/**
 * `transform(source, cloneFn, patternFn, updateFn, deleteFn?)` — `cloneFn`
 * is the CURRENT resolved `$clone` binding (translator.js#genTransformExpr
 * resolves `clone` the same way any other variable reference would, so a
 * `$clone :=` override in scope is honored) - jsonata's own
 * `evaluateTransformExpression` clones the source through
 * `environment.lookup('clone')`, throwing T2013 if that isn't callable,
 * rather than always running its own hard-coded clone (see CODE-REVIEW.md
 * M4). `patternFn`/`updateFn`/`deleteFn` are `(context) => value` closures
 * compiled from the transform's pattern/update/delete sub-expressions,
 * evaluated respectively against the clone and each match.
 */
function transform(source, cloneFn, patternFn, updateFn, deleteFn) {
  if (source === undefined) return undefined;
  if (typeof cloneFn !== 'function') throw err('T2013');
  const { applyFn } = require('./lambda');
  const result = applyFn(cloneFn, [source]);
  let matches = patternFn(result);
  if (matches === undefined) return result;
  if (!Array.isArray(matches)) matches = [matches];
  for (const match of matches) {
    const update = updateFn(match);
    if (update !== undefined) {
      if (!isPlainObject(update)) throw err('T2011', { value: update });
      for (const key of Object.keys(update)) {
        if (isPlainObject(match) || Array.isArray(match)) match[key] = update[key];
      }
    }
    if (deleteFn) {
      let deletions = deleteFn(match);
      if (deletions !== undefined) {
        const original = deletions;
        if (!Array.isArray(deletions)) deletions = [deletions];
        if (!deletions.every((d) => typeof d === 'string')) throw err('T2012', { value: original });
        if (isPlainObject(match)) {
          for (const key of deletions) delete match[key];
        }
      }
    }
  }
  return result;
}

/** `f ~> g` where both `f` and `g` are function VALUES (not immediate calls) — composes into a new function value, matching jsonata's `chainAST` desugaring. */
function composeFunctions(f, g) {
  const { applyFn } = require('./lambda');
  const composed = (x) => applyFn(g, [applyFn(f, [x])]);
  composed._jsonataArity = 1;
  return composed;
}

module.exports = { groupBy, groupByValues, sortTuples, sortValues, transform, composeFunctions };
